"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['test.py']
DATA_FILES = ["resources"]
OPTIONS = {
        'argv_emulation': True,
        "packages" : ["pygame"]
        }

setup(
    name="test_py2xxx",
    description="py2app test application",
    version="0.0.1",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
